GraWKosciWebInterface/Models/Concrete/WebGame.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GameLibrary.Abstract;
using GameLibrary.Concrete;
using GameLibrary.GameTools;

namespace GraWKosciWebInterface.Models.Concrete {
    public class WebGame {
        public IGame Game { get; set; }
        public IList<IPlayer> Players { get; set; } 
        public WebGame(IList<IPlayer> players ) {
            if (players == null) throw new ArgumentNullException("Brak graczy");
                Players = players;
                Game = new Game(players, 6, 5);
           
        }

    }
}

GraWKosciWebInterface/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameLibrary.Abstract;
using GameLibrary.GameTools;
using GraWKosci.DAL;
using GraWKosciWebInterface.Models.Concrete;

namespace GraWKosciWebInterface.Controllers
{
    public class HomeController : Controller
    {
        
        private WebGame game;
        private IList<IPlayer> players;
        public HomeController() {
            players = new List<IPlayer> {new Player("test1")};
           

            game = new WebGame(players);
        }
        // GET: Home
        public ActionResult Index()
        {
            game.Game.MakeOneRound(players[0]);
            return View(game);
        }
    }
}

GraWKosciWebInterface/Controllers/SqlPlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraWKosci.DAL;

namespace GraWKosciWebInterface.Controllers
{
    public class SqlPlayersController : Controller
    {
        private KosciContext db = new KosciContext();

        // GET: SqlPlayers
        public ActionResult Index()
        {
            return View(db.SqlPlayers.ToList());
        }

        // GET: SqlPlayers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlPlayer sqlPlayer = db.SqlPlayers.Find(id);
            if (sqlPlayer == null)
            {
                return HttpNotFound();
            }
            return View(sqlPlayer);
        }

        // GET: SqlPlayers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SqlPlayers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Score")] SqlPlayer sqlPlayer)
        {
            if (ModelState.IsValid)
            {
                db.SqlPlayers.Add(sqlPlayer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sqlPlayer);
        }

        // GET: SqlPlayers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlPlayer sqlPlayer = db.SqlPlayers.Find(id);
            if (sqlPlayer == null)
            {
                return HttpNotFound();
            }
            return View(sqlPlayer);
        }

        // POST: SqlPlayers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Score")] SqlPlayer sqlPlayer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sqlPlayer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sqlPlayer);
        }

        // GET: SqlPlayers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlPlayer sqlPlayer = db.SqlPlayers.Find(id);
            if (sqlPlayer == null)
            {
                return HttpNotFound();
            }
            return View(sqlPlayer);
        }

        // POST: SqlPlayers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SqlPlayer sqlPlayer = db.SqlPlayers.Find(id);
            db.SqlPlayers.Remove(sqlPlayer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GraWKosciWebInterface/Views/Home/Index.cshtml
@model GraWKosciWebInterface.Models.Concrete.WebGame

@{
    ViewBag.Title = "Index";
}

<h2>Losowanie w grze</h2>
<p>W grze wylosowano dla pracza: @Model.Players[0].Name</p>
<ul>
    @foreach (var wynik in @Model.Game.Cubes) {
        <li>Wynik dla kostki @wynik.GetLastThrowResult()</li>
    }
</ul>
@Html.ActionLink("Gracze","Index","SqlPlayers");

GraWKosciWebInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GraWKosciWebInterface/Views/SqlPlayers/Create.cshtml
@model GraWKosci.DAL.SqlPlayer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SqlPlayer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GraWKosciWebInterface/Views/SqlPlayers/Delete.cshtml
@model GraWKosci.DAL.SqlPlayer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SqlPlayer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GraWKosciWebInterface/Views/SqlPlayers/Details.cshtml
@model GraWKosci.DAL.SqlPlayer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SqlPlayer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GraWKosciWebInterface/Views/SqlPlayers/Edit.cshtml
@model GraWKosci.DAL.SqlPlayer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SqlPlayer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GraWKosciWebInterface/Views/SqlPlayers/Index.cshtml
@model IEnumerable<GraWKosci.DAL.SqlPlayer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>